config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :tweets, only: [:new, :index, :create]
    resources :follows 
  end


  resources :tweets, only: [:show, :edit, :update, :destroy] do
    resources :likes
    resources :comments 
  end

  resources :profiles

  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :commenter, class_name: "User"

  scope :ordered, -> {order(id: :desc)}

  validates :body, presence: true, length: { in: 1..140 }
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User', 
              counter_cache: :follows_count
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :body, presence: true, 
                  length: { maximum: 240 },
                  allow_nil: false


  belongs_to :author, class_name: "User"
  
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  #scope :ordered, -> {order(id: :desc)}

  def human_readable_created_at
    created_at.strftime("%b %-d, %Y - %l:%M %P")
  end

  def liked_by?(user)
    likes.any? { |like| like.user == user }
  end

  def find_like(user)
    likes.find_by(user: user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  

  has_many :tweets, foreign_key: "author_id", class_name: "Tweet", dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :followers, foreign_key: "receiver_id", 
            class_name: "Follow", 
            dependent: :destroy
  has_many :followed, foreign_key: "sender_id", 
            class_name: "Follow", 
            dependent: :destroy

  has_one :profile, dependent: :destroy

  def can_follow?(receiver)
    if self.followed.any? { |follow| follow.receiver_id == receiver.id }
      false
    else 
      true
    end
  end


  # Scopes

  scope :popular, -> { order(follows_count: :desc).take(5) }

  # Followers have a receiver id that matches up to a Users Id
  # Order by the number of receiver id's that match to a Users Id
  # Show the user with the most matches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @tweet = Tweet.find(params[:tweet_id])
    @comment = Comment.new
  end

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.create(comment_params)
    @comment.commenter_id = current_user.id
    
    respond_to do |format|
      if @comment.save
        format.turbo_stream
      else
        format.html {render :new, status: :unprocessable_entity}
      end
    end 
  end

  def destroy
    @comment = Comment.find_by(comment_params)
    
    if @comment.destroy
      redirecto_to tweet_path(params[:id])
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter_id, :body)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def index
  end

  def show
  end
  
  def new
    @follow = Follow.new
  end

  def create
    @follow = Follow.create(follow_params)
    return unless @follow.save

    redirect_to request.referrer
  end

  def destroy
    @follow = Follow.find_by(follow_params)
    #debugger
    return unless @follow.destroy

    redirect_to request.referrer
  end

  private

  def follow_params
    params.require(:follow).permit(:sender_id, :receiver_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @like = @tweet.likes.create(like_params)
    
    
  end

  def destroy
    @tweet = Tweet.find(params[:tweet_id])
    @like = @tweet.likes.find_by(like_params)
    
    @like.destroy
  end

  private

  def like_params
    params.require(:like).permit(:user_id, :tweet_id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)
    
    respond_to do |format|
      if @profile.save
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end 
    end    
  end

  def edit
    @user = User.find(params[:id])
    @profile = Profile.find_by(user_id: current_user.id)
  end

  def update
    @user = User.find(params[:id])
    @profile = Profile.find_by(user_id: current_user.id)

    respond_to do |format|
      if @profile.update(profile_params)
        format.turbo_stream
      else
        format.html {render :edit, status: :unprocessable_entity}
      end
    end 
  end

  def show
    @user = User.find(params[:id])
    @profile = Profile.find_by(user_id: params[:id])
  end

  private

  def profile_params
    params.require(:profile).permit(:age, :name, :bio)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def show
    @tweet = Tweet.find(params[:id])
  end

  def index
    timeline_ids = current_user.followed.pluck(:receiver_id) << current_user.id

    @tweets = Tweet.where('author_id IN (?)', timeline_ids)
                   .order(created_at: :desc)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @tweet = Tweet.find(params[:tweet_id])
    @user = User.find(@tweet.author_id)
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    
    respond_to do |format|
      if @tweet.destroy
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end


  private

  def tweet_params
    params.require(:tweet).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @popular = User.popular
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= comment.body %> <br>
<%= comment.commenter.email %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.after "tweet_#{@tweet.id}_new_comment", @comment %>

app/views/comments/index.html.erb
<% tweet.comments.each do |comment| %>
  <%= comment.body %> <br>
<% end %>

app/views/comments/new.html.erb
<%= turbo_frame_tag id="tweet_#{@tweet.id}_new_comment" do %>  
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "errors") %> prohibited this post from being saved:</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @comment, url: tweet_comments_path(@tweet)) do |form| %>
    <%= form.label :body %>
    <%= form.text_field :body %> <br>
    <%= form.submit %>
  <% end %>
<% end %>

app/views/likes/create.html.erb
<%= turbo_frame_tag "tweet_#{@tweet.id}" do %>
  <%= button_to tweet_like_path(@tweet, @like, like: { user_id: current_user.id, tweet_id: @tweet.id }),
      method: :delete,
      class: "btn btn-primary btn-sm d-flex align-items-center" do
  %>
    Liked
  <% end %>
<% end %>

app/views/likes/create.turbo_stream.erb
<%= turbo_stream.update "tweet_#{@tweet.id}" do %>
  <% like = @tweet.find_like(current_user) %>
    <% if @tweet.liked_by?(current_user) %>
      <%= button_to tweet_like_path(@tweet, @like, like: { user_id: current_user.id, tweet_id: @tweet.id }),
                    method: :delete,
                    class: "btn btn-primary btn-sm d-flex align-items-center" do
      %>
      Liked
    <% end %>
  <% else %>
      <%= button_to tweet_likes_path(@tweet, like: { user_id: current_user.id, tweet_id: @tweet.id }),
            class: "btn btn-outline-primary btn-sm d-flex" do
      %>
      Like
    <% end %>
  <% end %>
<% end %>

app/views/likes/destroy.html.erb
<%= turbo_frame_tag "tweet_#{@tweet.id}" do %>
  <%= button_to tweet_likes_path(@tweet, like: { user_id: current_user.id, tweet_id: @tweet.id }),
      class: "btn btn-outline-primary btn-sm d-flex" do
  %>
    Like
  <% end %>
<% end %>

app/views/likes/destroy.turbo_stream.erb
<%= turbo_stream.update "tweet_#{@tweet.id}" do %>
  <% like = @tweet.find_like(current_user) %>
    <% if @tweet.liked_by?(current_user) %>
      <%= button_to tweet_like_path(@tweet, @like, like: { user_id: current_user.id, tweet_id: @tweet.id }),
                    method: :delete,
                    class: "btn btn-primary btn-sm d-flex align-items-center" do
      %>
      Liked
    <% end %>
  <% else %>
      <%= button_to tweet_likes_path(@tweet, like: { user_id: current_user.id, tweet_id: @tweet.id }),
            class: "btn btn-outline-primary btn-sm d-flex" do
      %>
      Like
    <% end %>
  <% end %>
<% end %>

app/views/profiles/create.turbo_stream.erb
<%= turbo_stream.update "profile" %>

app/views/profiles/edit.html.erb
<%= turbo_frame_tag id="edit_profile" do %>
  <%= form_with(model: @profile, url: profile_path, method: :patch, profile: current_user.profile) do |form| %>
    <%= form.label :age %>
    <%= form.number_field :age, in: 1..100 %>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.label :bio %>
    <%= form.text_field :bio %>
    <%= form.submit %>
  <% end %>
<% end %>

app/views/profiles/new.html.erb
<%= turbo_frame_tag id="profile" do  %>
  <%= form_with(model: @profile, url: profiles_path, profile: @profile) do |form| %>
    <%= form.label :age %>
    <%= form.number_field :age, in: 1..100 %>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.label :bio %>
    <%= form.text_field :bio %>
    <%= form.submit %>
  <% end %>
<% end %>

app/views/profiles/show.html.erb
<%= turbo_frame_tag id="profile" do  %>
  <% if @user.profile && @user == current_user %>
    <%= turbo_frame_tag id="edit_profile" do %>
      <div>Name: <%= @user.profile.name %> </div>
      <div>Age: <%= @user.profile.age %> </div>
      <div>Bio: <%= @user.profile.bio %> </div>
      <%= link_to 'Edit Profile', edit_profile_path %> 
    <% end %>
  <% elsif @user.profile %>
    <div>Name: <%= @user.profile.name %> </div>
    <div>Age: <%= @user.profile.age %> </div>
    <div>Bio: <%= @user.profile.bio %> </div>
  <% elsif @user == current_user %>
    <%= link_to 'New Profile', new_profile_path %>
  <% end %>
<% end %>

app/views/profiles/update.turbo_stream.erb
<%= turbo_stream.update "profile" do %>
  <%= turbo_frame_tag id="edit_profile" do %>
    <div>Name: <%= @user.profile.name %> </div>
    <div>Age: <%= @user.profile.age %> </div>
    <div>Bio: <%= @user.profile.bio %> </div>
    <%= link_to 'Edit Profile', edit_profile_path %> 
  <% end %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="container mt-3 mb-4 p-3 border shadow-sm rounded hover-shadow-dark" style="background-color: #fff">
  <div class="row">
    <%= image_tag tweet.author.gravatar_url(default: :mm),
                  :class => "gravatar-home"
    %>
    <div class="row col ps-1">
      <%= link_to "#{tweet.author.email}",user_path(tweet.author.id), 
                  :class => "fw-semibold text-primary text-decoration-none"
      %>
      <div class="d-flex justify-content-between">
        <p class="text-secondary" style="display: inline-block">
          <%= tweet.human_readable_created_at %>
        </p>

        <% if tweet.author == current_user %>
          <%= button_to tweet_path(tweet), 
                                  method: :delete, 
                                  data: { turbo_confirm: 'Are you sure?'},
                                  :class => "btn btn-sm text-secondary me-4 opacity-75 delete-button",
                                  style: "border: none" do
          %> 
            <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                <path fill="currentColor" d="M9,3V4H4V6H5V19A2,2 0 0,0 7,21H17A2,2 0 0,0 19,19V6H20V4H15V3H9M9,8H11V17H9V8M13,8H15V17H13V8Z" />
              </svg>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="container mb-4">
      <p class="fs-5" style="word-wrap: break-word"><%= tweet.body %></p>
    </div>
    <div class="d-flex ms-2 ps-1 justify-content-between align-items-center">
      <div class="d-flex">
        <div class="button-field">
          <%= turbo_frame_tag "tweet_#{tweet.id}" do %>
            <% like = tweet.find_like(current_user) %>
            <% if tweet.liked_by?(current_user)%>
              <%= button_to tweet_like_path(tweet, like, like: { user_id: current_user.id, tweet_id: tweet.id }),
                            method: :delete,
                            class: "btn btn-primary btn-sm d-flex align-items-center" do
                        %>
                  Liked
              <% end %>
            <% else %>
              <%= button_to tweet_likes_path(tweet, like: { user_id: current_user.id, tweet_id: tweet.id }),
                            class: "btn btn-outline-primary btn-sm d-flex" do
                  %>
                    Like
                <% end %>
            <% end %>
          <% end %>
          <div class="d-flex justify-content-start align-items-center">
            <%= turbo_frame_tag id="tweet_#{tweet.id}_like_count" do %>
              <%= pluralize(tweet.likes.count, 'Like')%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="comment-field">
    <%= turbo_frame_tag id="tweet_#{tweet.id}_new_comment" do %>
      <%= link_to 'New Comment', new_tweet_comment_path(tweet.id), tweet: tweet %> <br>
      <%= render tweet.comments.ordered %>
    <% end %>
  </div>

</div>


<!--
<div class="tweet">
  <div class="body">
    <%= tweet.body %>
    <%= tweet.author.email %>
  </div> 
  
  <div class="button-field">
    <%= turbo_frame_tag id="tweet_#{tweet.id}", loading: :lazy do %>
      <% like = tweet.find_like(current_user) %>
      <% if tweet.liked_by?(current_user)%>
        <%= button_to 'Delete Like',
                      tweet_like_path(tweet, like, like: {user_id: current_user.id, tweet_id: tweet.id}),
                      method: :delete
                      %>
      <% else %>
        <%= button_to 'like', tweet_likes_path(tweet, like: {user_id: current_user.id, tweet_id: tweet.id})%>
      <% end %>
    <% end %>
  </div>
  
  <div class="comment-field">
    <%= turbo_frame_tag id="tweet_#{tweet.id}_like_count" do %>
      <%= pluralize(tweet.likes.count, 'Like')%>
    <% end %>
    
    <%= turbo_frame_tag id="tweet_#{tweet.id}_new_comment" do %>
      <%= link_to 'New Comment', new_tweet_comment_path(tweet.id), tweet: tweet %> <br>
      <%= render tweet.comments.ordered %>
    <% end %>
  </div>
  <% if tweet.author == current_user %>
    <%= button_to 'Delete', tweet_path(tweet.id), method: :delete, data: { turbo_confirm: 'Are you sure?'}  %>
  <% end %>
</div>
-->

app/views/tweets/create.turbo_stream.erb
<%= turbo_stream.prepend "tweets", @tweet %>

app/views/tweets/destroy.turbo_stream.erb
<%= turbo_stream.update "tweets" %>

app/views/tweets/index.html.erb
<div class="bg-light">
  <div class="container pt-5 pt-2">
    <h5 class="text-start text-secondary">Latest Posts</h5>
    <div class="row justify-content-between mt-2">
      <div class="col-8">
        <div class="card"><%= turbo_frame_tag id="new_tweet", src:new_user_tweet_path(current_user), loading: :lazy %></div>
          <div id="tweets">
            <%= render @tweets %>
          </div>
      </div>
    </div>
  </div>
</div>


<!-- <%= render 'shared/sidebar' %> -->

app/views/tweets/new.html.erb
<%= turbo_frame_tag id="new_tweet" do %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @tweet, url: user_tweets_path(current_user), tweet: @tweet)  do |form| %>
    <%= form.text_area(:body, cols: 30, rows:10, placeholder: "Write and share your thoughts here!") %> <br>
    <%= form.submit %>
  <% end %>
<% end %>

app/views/tweets/show.html.erb
<%= render 'tweet', tweet: @tweet %>

app/views/users/_follow_buttons.html.erb
<div>
  <% if current_user.can_follow?(user) %>
    <%= button_to 'Follow User', user_follows_path(current_user.id),
        params: { follow: {
            sender_id: current_user.id,
            receiver_id: user.id
          }
        }
    %>
  <% else %>
    <%= button_to 'Unfollow', user_follow_path(current_user.id, user.id),
        method: :delete,
        params: { follow: {
            sender_id: current_user.id,
            receiver_id: user.id
          }
        }
    %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, url: user_path(current_user), method: :patch) do |form| %>
  <%= form.text_area(:bio, cols: 20, rows:5, placeholder: "Share a bit about yourself") %> <br>
  <%= form.submit %>
<% end %>

<%= params %>

app/views/users/_user.html.erb
<%= user.email %>

app/views/users/edit.html.erb
<div class="profile">
  <div class="profile-card">
    <div class="profile-pic"></div>
    <div class="email"></div>
    <div class="bio">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li><%= render 'user', user: user %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="profile">
  <div class="profile-card">
    <div class="profile-pic">
      <%= image_tag current_user.gravatar_url,:class => "gravatar" %>
    </div>
    <div class="email"></div>
    <div class="bio">
      <%= turbo_frame_tag id="profile", src: profile_path  %>
      
      <%= render 'follow_buttons', user: @user %>
    </div>
  </div>
</div>